### ISSUE TITLE
no such file or directory, open './bin/1.html'

### ISSUE THREAD

**Issue by Lxxyx** [timqian/jsCodeStructure#8]
Node 6.2.2。
use in my project, then:

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './bin/1.html'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/.js-code-structure_npminstall/js-code-structure/0.1.9/js-code-structure/bin/jss.js:18:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)

**Comment by timqian** [comment]
Sorry for this stupid bug,and thanks for your quick report. The bug has been fixed. Plz reinstall the package and try again

**Comment by Lxxyx** [comment]
3Q~
